# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Adithya/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-2736-Adithya-PC/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.cache/wt [current_project]
set_property parent.project_path C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/4_bit_Add_Sub_Unit/4_bit_Add_Sub_Unit.srcs/sources_1/new/ADD_SUB_4bit.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/3_bit_Adder/3_bit_Adder.srcs/sources_1/new/Adder_3bit.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/Program_Counter/Program_Counter.srcs/sources_1/imports/new/Counter.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/Program_Counter/Program_Counter.srcs/sources_1/imports/new/D_FF.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/Mux_2_1_3bit/Project_9_2.srcs/sources_1/new/Decoder_1_to_2.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/Mux_8_1/Lab9.srcs/sources_1/imports/new/Decoder_2_to_4.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/Mux_8_1/Lab9.srcs/sources_1/imports/new/Decoder_3_to_8.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/4_bit_Add_Sub_Unit/4_bit_Add_Sub_Unit.srcs/sources_1/imports/new/FA.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/4_bit_Add_Sub_Unit/4_bit_Add_Sub_Unit.srcs/sources_1/imports/new/HA.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/Instruction_Decoder/Instruction_Decoder.srcs/sources_1/new/ID.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/progam_rom/progam_rom.srcs/sources_1/imports/new/LUT_16_7.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/new/LUT_16_7.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/Mux_2_1_3bit/Project_9_2.srcs/sources_1/new/MUX_2_1_3bit.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/Mux_2_1_4bit/Project_9_3.srcs/sources_1/new/MUX_2_1_4bit.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/Mux_8_1/Lab9.srcs/sources_1/new/MUX_8_1_4bit.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/new/Nanoprocessor_Group_11.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/4_bit_Add_Sub_Unit/4_bit_Add_Sub_Unit.srcs/sources_1/imports/new/RCA_4.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/register_bank/LAB09.srcs/sources_1/imports/sources_1/new/Reg.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/register_bank/LAB09.srcs/sources_1/new/Register_Bank.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/imports/digital_design_labs/Program_Counter/Program_Counter.srcs/sources_1/imports/new/Slow_Clk.vhd
  C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/sources_1/new/nanoprocessor_with_7_segment_display.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/constrs_1/imports/digital_design_labs/Basys3Labs.xdc
set_property used_in_implementation false [get_files C:/Users/Adithya/digital_design_labs/Nanoprocessor/Nanoprocessor.srcs/constrs_1/imports/digital_design_labs/Basys3Labs.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top nanoprocessor_with_7_segment_display -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef nanoprocessor_with_7_segment_display.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file nanoprocessor_with_7_segment_display_utilization_synth.rpt -pb nanoprocessor_with_7_segment_display_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
